server:
  port: 1213


#management:
#  server:
#    port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
        
      base-path: /myactuator       
  endpoint:
     shutdown:
       enabled: true



  info:
    git:
      enabled: true

    build:
      enabled: true
      
    env:
      enabled: true
      
#info:  
# createdBy: Pavan
# modified: 22May22 

logging:
  level:
    com:
      zensar: debug
      
      
    

#springfox:
# documentation:
#  auto-startup: false

spring:
 datasource:
  url: jdbc:mysql://mysql:1006/fullstack
  username: root
  password: test
 jpa:
  hibernate:
   ddl-auto: create
  show-sql: true
  properties:
   hibernate:
     format_sql: true
     dialect: org.hibernate.dialect.MySQLDialect
     
 